# Generated by Django 4.1.5 on 2023-01-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('interest', models.CharField(choices=[('KIDS_CODING', 'Kids Coding (5-12)'), ('ADULT_CODING', 'Adult Coding ( 13+ )'), ('SEO', 'Search Engine Optimization'), ('SERVER_ADMIN', 'Server Administration')], max_length=50)),
                ('learning_path', models.CharField(choices=[('SELF_HELP', 'Self Help Route'), ('CLASSROOM', 'Classroom Learning')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
    ]
