# Generated by Django 4.1.5 on 2023-01-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='interest',
            field=models.CharField(choices=[{'KIDS_CODING', 'Kids Coding (5-12yrs)'}, {'Adult Coding (13+yrs)', 'ADULT_CODING'}, {'Search Engine Optimization', 'SEO'}, {'Server Administration', 'SERVER_ADMIN'}], max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='learning_path',
            field=models.CharField(choices=[('Self Help Route', 'SELF_HELP'), ('Online Classroom', 'CLASSROOM')], max_length=50),
        ),
    ]
