# Generated by Django 4.1.5 on 2023-01-31 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_interest_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_date']},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='learning_path',
        ),
        migrations.AddField(
            model_name='reservation',
            name='age',
            field=models.CharField(default='25', max_length=2),
        ),
        migrations.AddField(
            model_name='reservation',
            name='boolean',
            field=models.BooleanField(default=True, verbose_name='Do you want your child to code?'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='city',
            field=models.CharField(default='New York', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Time'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='interests',
            field=models.CharField(choices=[('SEO', 'SEO'), ('KIDS', 'Kids'), ('CODING', 'Coding'), ('SERVER', 'Server Administration'), ('OTHER', 'Other Tech')], default='SEO', max_length=200),
        ),
        migrations.AddField(
            model_name='reservation',
            name='learnings',
            field=models.CharField(choices=[('CLASS', 'Class'), ('SINGLE', 'Single')], default='Class', max_length=200),
        ),
        migrations.AddField(
            model_name='reservation',
            name='other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='state',
            field=models.CharField(default='NY', max_length=2),
        ),
        migrations.AddField(
            model_name='reservation',
            name='url',
            field=models.SlugField(default='https://sample.com'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='zipcode',
            field=models.IntegerField(default='90210'),
        ),
    ]
