# Generated by Django 4.1.5 on 2023-01-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='url',
            field=models.URLField(default='https://sample.com'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='zipcode',
            field=models.CharField(default='90210', max_length=5),
        ),
    ]
