# Generated by Django 4.1.5 on 2023-02-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_reservation_url_alter_reservation_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='learnings',
        ),
        migrations.AddField(
            model_name='reservation',
            name='more_options',
            field=models.CharField(default='Class', max_length=200),
        ),
        migrations.AddField(
            model_name='reservation',
            name='options',
            field=models.CharField(default='SEO', max_length=200),
        ),
    ]
