# Generated by Django 4.1.5 on 2023-02-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_remove_reservation_interests_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='options',
            new_name='interest_options',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='more_options',
        ),
        migrations.AddField(
            model_name='reservation',
            name='learning_styles',
            field=models.CharField(default='Visual', max_length=200),
        ),
    ]
