# Generated by Django 4.1.5 on 2023-02-05 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_rename_options_reservation_interest_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='interest_options',
            new_name='interestOptions',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='learning_styles',
            new_name='learningOptions',
        ),
    ]
