# Generated by Django 4.1.5 on 2023-02-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_rename_interest_options_reservation_interestoptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='Email', max_length=250),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='first_name',
            field=models.CharField(default='First name', max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(default='Last name', max_length=50),
        ),
    ]
