# Generated by Django 4.1.5 on 2023-02-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_alter_reservation_email_alter_reservation_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='boolean',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='Email', max_length=120),
        ),
    ]
