# Generated by Django 4.1.5 on 2023-02-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_remove_reservation_boolean_alter_reservation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='interestOptions',
            field=models.CharField(default='SEO', max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='learningOptions',
            field=models.CharField(default='Visual', max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='url',
            field=models.URLField(default='https://example.com'),
        ),
    ]
