# Generated by Django 4.1.5 on 2023-02-06 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_alter_reservation_interestoptions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='interestOptions',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='learningOptions',
        ),
    ]
